# Generated by Django 4.2.2 on 2023-10-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='subtitle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
