# Generated by Django 4.2.2 on 2023-10-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkprofile', '0002_campaign_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='image',
        ),
        migrations.AddField(
            model_name='campaign',
            name='background_image',
            field=models.ImageField(null=True, upload_to='background_images/'),
        ),
    ]
