# Generated by Django 4.2.2 on 2023-10-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkprofile', '0006_priorities'),
    ]

    operations = [
        migrations.CreateModel(
            name='prioritiesExamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priorities_heading', models.TextField()),
                ('priorities_description', models.TextField()),
                ('priorities_image', models.ImageField(null=True, upload_to='priorities_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='priorities',
            name='news_description',
        ),
        migrations.RemoveField(
            model_name='priorities',
            name='news_heading',
        ),
        migrations.RemoveField(
            model_name='priorities',
            name='news_image',
        ),
        migrations.AlterField(
            model_name='priorities',
            name='title_description',
            field=models.TextField(),
        ),
    ]
