# Generated by Django 4.2.2 on 2023-10-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkprofile', '0008_alter_priorities_title_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prioritiesExamples',
            new_name='priorityExamples',
        ),
    ]
