# Generated by Django 4.2.2 on 2023-10-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkprofile', '0009_rename_prioritiesexamples_priorityexamples'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_name', models.TextField()),
                ('meet_description', models.TextField()),
                ('meet_image', models.ImageField(null=True, upload_to='meet_images/')),
            ],
        ),
    ]
