# Generated by Django 4.2.2 on 2023-10-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkprofile', '0010_meet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_name', models.TextField()),
                ('testimonial_description', models.TextField()),
                ('testimonial_residence', models.TextField()),
                ('testimonial_image', models.ImageField(null=True, upload_to='testimonial_images/')),
            ],
        ),
    ]
