# Generated by Django 4.2.2 on 2023-10-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkprofile', '0011_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_price', models.CharField(max_length=200, null=True)),
                ('product_image', models.ImageField(null=True, upload_to='products_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='testimonial_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='testimonial_residence',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
