# Generated by Django 4.2.6 on 2023-10-24 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkprofile', '0017_news_soundcloud_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='soundcloud_url',
            new_name='vimeo',
        ),
    ]
