# Generated by Django 4.2.6 on 2023-10-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkprofile', '0020_mission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='content',
            new_name='quote',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='category',
        ),
        migrations.AddField(
            model_name='mission',
            name='description1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='description2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='description3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='image2',
            field=models.ImageField(null=True, upload_to='mission_images/'),
        ),
    ]
