# Generated by Django 4.2.6 on 2023-11-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkprofile', '0024_products_customer_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
