# Generated by Django 4.2.6 on 2023-11-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkprofile', '0026_checkoutorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutorder',
            name='postcode',
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='product_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='size',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='town_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
