# Generated by Django 4.2.6 on 2023-11-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkprofile', '0028_alter_checkoutorder_delivery_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='otherPriorities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
