# Generated by Django 4.2.6 on 2023-11-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkprofile', '0029_otherpriorities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='iframe',
            new_name='youtube_url',
        ),
    ]
