# Generated by Django 4.2.6 on 2023-11-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkprofile', '0031_category_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
