# Generated by Django 4.2.6 on 2023-11-12 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkprofile', '0032_news_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='year',
        ),
        migrations.AddField(
            model_name='news',
            name='archive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='mkprofile.newsarchive'),
        ),
    ]
